service: membersOnly
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  memorySize: 128
  deploymentMethod: direct
functions:
  app:
    handler: tsbuild/app.handler
    events:
      - httpApi: '*'
custom:
  dotenv:
    path: .env